"""
Example ToothFairy4 algorithm template.

The container reads a CBCT volume from the input socket `cbct-image` and writes a
JSON diagnostic report to the output socket `diagnostic-imaging-report`.
"""

import glob
import json
from pathlib import Path

import SimpleITK
import torch


INPUT_PATH = Path("/input")
OUTPUT_PATH = Path("/output")
MODEL_PATH = Path("/opt/ml/model")


def run():
    interface_key = get_interface_key()
    handler = {
        ("cbct-image",): interf0_handler,
    }[interface_key]
    return handler()


def interf0_handler():
    cbct_image = load_image_file(location=INPUT_PATH / "images" / "cbct")
    cbct_array = SimpleITK.GetArrayFromImage(cbct_image)

    _show_torch_cuda_info()
    report = run_model(cbct_image=cbct_image, cbct_array=cbct_array)

    OUTPUT_PATH.mkdir(parents=True, exist_ok=True)
    write_json_file(
        location=OUTPUT_PATH / "diagnostic-imaging-report.json",
        content={"report": report},
    )

    return 0


def run_model(*, cbct_image, cbct_array) -> str:
    """Placeholder model entrypoint for future implementations."""
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Using device: {device}")

    model = torch.nn.Linear(10, 1).to(device)
    dummy_input = torch.randn(1, 10, device=device)
    _ = model(dummy_input)

    resource = MODEL_PATH / "a_tarball_subdirectory" / "some_tarball_resource.txt"
    if resource.exists():
        print(resource.read_text(encoding="utf-8"))

    print(f"CBCT size: {cbct_image.GetSize()}")
    print(f"CBCT spacing: {cbct_image.GetSpacing()}")
    print(f"CBCT array shape: {cbct_array.shape}")

    return (
        "This is a placeholder diagnostic imaging report generated by the "
        "ToothFairy4 example algorithm. Replace run_model() with the real model."
    )


def get_interface_key():
    inputs = load_json_file(location=INPUT_PATH / "inputs.json")
    socket_slugs = [value["socket"]["slug"] for value in inputs]
    return tuple(sorted(socket_slugs))


def load_json_file(*, location):
    with open(location, encoding="utf-8") as f:
        return json.loads(f.read())


def write_json_file(*, location, content):
    with open(location, "w", encoding="utf-8") as f:
        f.write(json.dumps(content, indent=4))


def load_image_file(*, location):
    input_files = sorted(glob.glob(str(location / "*.mha")))
    if not input_files:
        raise RuntimeError(f"No .mha CBCT image found in {location}")
    if len(input_files) > 1:
        print(f"Multiple .mha files found in {location}; using {Path(input_files[0]).name}")
    return SimpleITK.ReadImage(input_files[0])


def _show_torch_cuda_info():
    print("=+=" * 10)
    print("Collecting Torch CUDA information")
    print(f"Torch CUDA is available: {(available := torch.cuda.is_available())}")
    if available:
        print(f"\tnumber of devices: {torch.cuda.device_count()}")
        print(f"\tcurrent device: {(current_device := torch.cuda.current_device())}")
        print(f"\tproperties: {torch.cuda.get_device_properties(current_device)}")
    print("=+=" * 10)


if __name__ == "__main__":
    raise SystemExit(run())
