"""Example Bite2Text algorithm template.

The container reads two IOS scans and one intraoral photo and writes a JSON
diagnostic report to the output socket ``diagnostic-imaging-report``.
"""

import glob
import json
from pathlib import Path

import torch


INPUT_PATH = Path("/input")
OUTPUT_PATH = Path("/output")
MODEL_PATH = Path("/opt/ml/model")


def run():
    inputs = load_json_file(location=INPUT_PATH / "inputs.json")
    handler = select_handler(inputs)
    return handler()


def select_handler(inputs: list[dict]) -> callable:
    slug_set = {
        str((value.get("socket") or {}).get("slug") or "").strip()
        for value in inputs
    }

    lower_slugs = {"3d-lower-teeth-scan", "ios-lower-scan"}
    upper_slugs = {"3d-upper-teeth-scan", "ios-upper-scan"}
    photo_slugs = {"2d-intraoral-photographs", "intraoral-photo"}

    has_lower = any(slug in slug_set for slug in lower_slugs)
    has_upper = any(slug in slug_set for slug in upper_slugs)
    has_photo = any(slug in slug_set for slug in photo_slugs)

    if has_lower and has_upper and has_photo:
        return interf0_handler

    raise RuntimeError(
        "Unsupported input socket configuration. "
        f"Found slugs: {sorted(slug for slug in slug_set if slug)}"
    )


def interf0_handler():
    lower_scan = load_single_file_compat(
        preferred_files=(INPUT_PATH / "3d-lower-teeth-scan.obj",),
        fallback_locations=(INPUT_PATH / "files" / "ios-lower",),
        fallback_patterns=("*.obj", "*.stl"),
    )
    upper_scan = load_single_file_compat(
        preferred_files=(INPUT_PATH / "3d-upper-teeth-scan.obj",),
        fallback_locations=(INPUT_PATH / "files" / "ios-upper",),
        fallback_patterns=("*.obj", "*.stl"),
    )
    intraoral_photos = load_files_compat(
        preferred_location=INPUT_PATH / "images" / "2d-intraoral-photographs",
        fallback_location=INPUT_PATH / "images" / "intraoral-photo",
        patterns=("*.mha", "*.tif", "*.tiff", "*.jpg", "*.jpeg", "*.png", "*.dzi"),
    )

    _show_torch_cuda_info()
    report = run_model(
        lower_scan_path=lower_scan,
        upper_scan_path=upper_scan,
        intraoral_photo_paths=intraoral_photos,
    )

    OUTPUT_PATH.mkdir(parents=True, exist_ok=True)
    write_json_file(
        location=OUTPUT_PATH / "diagnostic-imaging-report.json",
        content={"report": report},
    )

    return 0


def run_model(*, lower_scan_path: Path, upper_scan_path: Path, intraoral_photo_paths: list[Path]) -> str:
    """Placeholder model entrypoint for future implementations."""
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Using device: {device}")

    model = torch.nn.Linear(10, 1).to(device)
    dummy_input = torch.randn(1, 10, device=device)
    _ = model(dummy_input)

    resource = MODEL_PATH / "a_tarball_subdirectory" / "some_tarball_resource.txt"
    if resource.exists():
        print(resource.read_text(encoding="utf-8"))

    print(f"Lower IOS file: {lower_scan_path.name} ({lower_scan_path.stat().st_size} bytes)")
    print(f"Upper IOS file: {upper_scan_path.name} ({upper_scan_path.stat().st_size} bytes)")
    print(f"Intraoral photos detected: {len(intraoral_photo_paths)}")
    for photo_path in intraoral_photo_paths:
        print(f" - {photo_path.name} ({photo_path.stat().st_size} bytes)")

    return (
        "This is a placeholder diagnostic imaging report generated by the "
        "Bite2Text example algorithm. Replace run_model() with the real model."
    )


def load_json_file(*, location):
    with open(location, encoding="utf-8") as f:
        return json.loads(f.read())


def write_json_file(*, location, content):
    with open(location, "w", encoding="utf-8") as f:
        f.write(json.dumps(content, indent=4))


def load_single_file_compat(
    *,
    preferred_files: tuple[Path, ...],
    fallback_locations: tuple[Path, ...],
    fallback_patterns: tuple[str, ...],
) -> Path:
    for file_path in preferred_files:
        if file_path.exists():
            return file_path

    for location in fallback_locations:
        for pattern in fallback_patterns:
            input_files = sorted(glob.glob(str(location / pattern)))
            if not input_files:
                continue
            if len(input_files) > 1:
                print(f"Multiple files found in {location}; using {Path(input_files[0]).name}")
            return Path(input_files[0])

    fallback_desc = ", ".join(str(path) for path in fallback_locations)
    raise RuntimeError(
        "No compatible input file found. "
        f"Checked preferred files: {[str(path) for path in preferred_files]}, "
        f"fallback locations: {fallback_desc}, patterns: {fallback_patterns}"
    )


def load_files_compat(*, preferred_location: Path, fallback_location: Path, patterns: tuple[str, ...]) -> list[Path]:
    files: list[Path] = []
    for location in (preferred_location, fallback_location):
        for pattern in patterns:
            files.extend(Path(path) for path in glob.glob(str(location / pattern)))

    unique_files = sorted({path.resolve(): path for path in files}.values(), key=lambda path: path.name)
    if not unique_files:
        raise RuntimeError(
            "No intraoral photo found. "
            f"Checked {preferred_location} and {fallback_location}; tried patterns {patterns}"
        )
    return unique_files


def _show_torch_cuda_info():
    print("=+=" * 10)
    print("Collecting Torch CUDA information")
    print(f"Torch CUDA is available: {(available := torch.cuda.is_available())}")
    if available:
        print(f"\tnumber of devices: {torch.cuda.device_count()}")
        print(f"\tcurrent device: {(current_device := torch.cuda.current_device())}")
        print(f"\tproperties: {torch.cuda.get_device_properties(current_device)}")
    print("=+=" * 10)


if __name__ == "__main__":
    raise SystemExit(run())
