"""Example Bite2Text algorithm template.

The container reads two IOS scans and one intraoral photo and writes a JSON
diagnostic report to the output socket ``diagnostic-imaging-report``.
"""

import glob
import json
from pathlib import Path

import torch


INPUT_PATH = Path("/input")
OUTPUT_PATH = Path("/output")
MODEL_PATH = Path("/opt/ml/model")


def run():
    interface_key = get_interface_key()
    handler = {
        ("2d-intraoral-photographs", "3d-lower-teeth-scan", "3d-upper-teeth-scan"): interf0_handler,
    }[interface_key]
    return handler()


def interf0_handler():
    lower_scan = load_single_file(location=INPUT_PATH / "files" / "ios-lower", pattern="*.stl")
    upper_scan = load_single_file(location=INPUT_PATH / "files" / "ios-upper", pattern="*.stl")
    intraoral_photo = load_single_file(
        location=INPUT_PATH / "images" / "intraoral-photo",
        pattern="*.tif*",
    )

    _show_torch_cuda_info()
    report = run_model(
        lower_scan_path=lower_scan,
        upper_scan_path=upper_scan,
        intraoral_photo_path=intraoral_photo,
    )

    OUTPUT_PATH.mkdir(parents=True, exist_ok=True)
    write_json_file(
        location=OUTPUT_PATH / "diagnostic-imaging-report.json",
        content={"report": report},
    )

    return 0


def run_model(*, lower_scan_path: Path, upper_scan_path: Path, intraoral_photo_path: Path) -> str:
    """Placeholder model entrypoint for future implementations."""
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Using device: {device}")

    model = torch.nn.Linear(10, 1).to(device)
    dummy_input = torch.randn(1, 10, device=device)
    _ = model(dummy_input)

    resource = MODEL_PATH / "a_tarball_subdirectory" / "some_tarball_resource.txt"
    if resource.exists():
        print(resource.read_text(encoding="utf-8"))

    print(f"Lower IOS file: {lower_scan_path.name} ({lower_scan_path.stat().st_size} bytes)")
    print(f"Upper IOS file: {upper_scan_path.name} ({upper_scan_path.stat().st_size} bytes)")
    print(f"Intraoral photo: {intraoral_photo_path.name} ({intraoral_photo_path.stat().st_size} bytes)")

    return (
        "This is a placeholder diagnostic imaging report generated by the "
        "Bite2Text example algorithm. Replace run_model() with the real model."
    )


def get_interface_key():
    inputs = load_json_file(location=INPUT_PATH / "inputs.json")
    socket_slugs = [value["socket"]["slug"] for value in inputs]
    return tuple(sorted(socket_slugs))


def load_json_file(*, location):
    with open(location, encoding="utf-8") as f:
        return json.loads(f.read())


def write_json_file(*, location, content):
    with open(location, "w", encoding="utf-8") as f:
        f.write(json.dumps(content, indent=4))


def load_single_file(*, location: Path, pattern: str) -> Path:
    input_files = sorted(glob.glob(str(location / pattern)))
    if not input_files:
        raise RuntimeError(f"No input file matching '{pattern}' found in {location}")
    if len(input_files) > 1:
        print(f"Multiple files found in {location}; using {Path(input_files[0]).name}")
    return Path(input_files[0])


def _show_torch_cuda_info():
    print("=+=" * 10)
    print("Collecting Torch CUDA information")
    print(f"Torch CUDA is available: {(available := torch.cuda.is_available())}")
    if available:
        print(f"\tnumber of devices: {torch.cuda.device_count()}")
        print(f"\tcurrent device: {(current_device := torch.cuda.current_device())}")
        print(f"\tproperties: {torch.cuda.get_device_properties(current_device)}")
    print("=+=" * 10)


if __name__ == "__main__":
    raise SystemExit(run())
